name: Build Kernel
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: sysdrivers/kernel_build_action@main
      with:
          kernel-url: https://github.com/sysdrivers/kernel_h7000_bbk
          kernel-branch: master
          config: h7000_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 9
          clang-version: r399163b
          python-27: true
          disable-lto: true
          anykernel3: true
